### ISSUE TITLE
Issues to connect to S3 bucket

### ISSUE THREAD

**Issue by gregorycottone** [fsspec/jupyter-fsspec#71]
Hello,

I'm trying to set up jupyter-fsspec in my jupyter server.

After having installed it through pip (I have the version 0.3.0), and after having created a file named jupyter-fsspec.yaml inside the /home/jovyan/.jupyter folder with the following content:

```
sources:
  - name: "BucketXXX"
    path: "s3://bucket-xxx"
    args: []
    kwargs:
      anon: false
      client_kwargs:
        endpoint_url: "https://s3.provider.com"
```

I'm still not able to see the content of the S3 bucket.

This is a screenshot of what I see:

![Image](https://github.com/user-attachments/assets/4c852b80-b65d-4c86-83a2-231559646053)

From the inspect console tool of my browser I see this:

```
[FSSpec] Request config:
{"status":"success","description":"Retrieved available filesystems from configuration file.","content":[]}
logger.ts:14 [FSSpec] Successfully retrieved config:{"filesystems":{},"status":"success"}
logger.ts:14 [FSSpec] Populate filesystems: 
{}
```

Note that if I create a jupyter notebook with the following content it works perfectly as expected:

```
import fsspec

fs = fsspec.filesystem('s3')

list_files = fs.ls("s3://bucket-xxx", detail=False)

print(list_files)
```

Also the following jupyter notebook works:

```
import s3fs

s3 = s3fs.S3FileSystem(anon=False)

list_files = s3.ls('s3://bucket-xxx')

print(list_files)
```

**Comment by gregorycottone** [comment]
Hi @RRosio and thank you for your answer.

If I run your code I get this: `'/home/jovyan/.jupyter'`. Inside this folder I have a file called `jupyter-fsspec.yaml` which has the following content:

```
sources:
  - name: "BucketXXX"
    path: "s3://bucket-xxx"
    args: []
    kwargs:
      anon: false
      client_kwargs:
        endpoint_url: "https://s3.provider.com"
```

**Comment by martindurant** [comment]
@RRosio - we have a test that looks just like this case, no?

**Comment by sgrenf95** [comment]
Hi @martindurant and thank you for the response, if you refer to the example in the [jupyter-fsspec documentation](https://jupyter-fsspec.readthedocs.io/en/latest/#jupyter-fsspec-documentation), this is what it is written:
```
sources:
  - name: "Cell filter repo"
    path: "/Users/finnmertens/cfilter/jupyterlab"
    protocol: "file"
  - name: "Averager project"
    path: "file:///Users/finnmertens/averager"
  - name: "Remote MyBucket
    path: "s3://mybucket"
    args: []
    kwargs:
      anon: false
      key: "my-access-key"
      secret: "my-secret-key"
      client_kwargs:
        endpoint_url: "https://s3.provider.com"
```

I followed the steps of the documentation, but still it doesn't work in my case.
